services:
  - type: web
    name: ecom-proj
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./ecom-proj/Dockerfile
    rootDir: ecom-proj
    envVars:
      - key: JAVA_VERSION
        value: 21
    healthCheckPath: /
