services:
  - type: web
    name: ecom-proj
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/ecom-proj-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21

